---
version: 2
workflows:
  version: 2
  nightly:
    triggers:
      - schedule:
          cron: "0 23 */2 * *"
          filters:
            branches:
              only:
                - master
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Login to registry
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: Build the image
          command: docker build -t saschagrunert/build-rust .
      - run:
          name: Push the image
          command: docker push saschagrunert/build-rust:latest
